### PR TITLE
Improved deployment process and prepare for OCP CI

### PR DESCRIPTION
**Pull request by omeryahud**
Improved the deployment process to make it easier to deploy and update the operator

Modified Make targets:
- `manifests`:
		Now generates manifests using the `IMAGE_REGISTRY`, `IMAGE_TAG` and `OPERATOR_IMAGE` variables defined in the makefile

New Make targets:
- `deploy`:
		Can be used in order to deploy the operator to a cluster along with upstream Kubevirt and CDI
- `ocp-ci-manifests`:
		Used to generate manifests specifically for OCP CI test lanes
- `ocp-ci-deploy`:
		Used to deploy the operator build by the OCP CI system

Functional tests changes:
	Refactored the functional test suite to remove duplicate tests and activate tests that require a new version
	of OCP, now that we can provide it with OCP CI for CI or with CRC/Quicklab for development

Common usages of new make targets:

	$ export IMAGE_REGISTRY=quay.io/oyahud IMAGE_TAG=devel
	$ make container-build-operator && make container-push-operator
	$ make deploy

This flow will build the operator, push it to the registry defined by the environment,
generate the required manifests and apply them to the cluster the user is currently logged in to.

**NOTE**: manifests are now generated with image digests instead of floating tags.

Signed-off-by: Omer Yahud <oyahud@redhat.com>

**What this PR does / why we need it**:
This PR simplifies the build/push/deploy flow of the operator, while also preparing for OCP CI integration

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
NONE

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by akrejcir** [comment]
Looks good. What is the benefit of using image digest instead of tag?

**Comment by omeryahud** [comment]
> Looks good. What is the benefit of using image digest instead of tag?

When using a tag and pushing to it, you have to either delete and create the operator deployment, or set pull policy to `Always` and delete the operator pods in order for them to update, when using digests in this flow, you could repeatedly run
```
$ export IMAGE_REGISTRY=quay.io/oyahud IMAGE_TAG=devel
$ make container-build-operator && make container-push-operator
$ make deploy
```
And have the deployment patched with the new image digest and redeploy the pods, saves some manual work and underlying details that might cause confusion to someone who is not too familiar with the project

**Comment by akrejcir** [comment]
Ok, that makes sense.

**Comment by omeryahud** [comment]
Took care of CI, I skipped the template-validator test that requires ocp 4, I will re-enable it on a following PR with ocp ci presubmit
@akrejcir @ksimon1 Can you take a quick look again?

**Comment by omeryahud** [comment]
/hold
theres a tiny nit I need to fix

**Comment by omeryahud** [comment]
Added `sort -V` here https://github.com/kubevirt/kubevirt-ssp-operator/pull/221/files#diff-9c562006fac52e436d79bfd6fe2fa7c6R18 to make sure versions are properly sorted and the latest version is deployed

**Pull request merged**
